# Hugo variables
#
baseurl = "https://alperor.us/"
title = "Alper Orus"
theme = "picorus"
languagecode = "en"
defaultcontentlanguage = "tr"
defaultcontentlanguageinsubdir = false

enableRobotsTXT = true
paginate = 6
summarylength = 25

[taxonomies]
  category = "categories"
  tag = "tags"
  series ="series"

[params]
author = "Alper"
description = "Alper Orus Personal Website"
keywords = "blog, photography, design, alper, personal, orus, eorus, linux, wordpress, hugo, frontend"
info = "Front End Developer, Photographer, Blogger and a Passionate Linux Enthusiast"
footercontent = "Fall in love with some activity, and do it! Nobody ever figures out what life is all about, and it doesn’t matter."
avatarURL = "images/avatar.jpg"
dateFormat = "02.01.2006"
since = 2019
googleSiteVerification = "m0snGinntNZeCcUtR-3VL4xPM63J6sqyfvTmO9wFxOE"

[languages]
    [languages.en]
        languagename = "EN"
        contentDir = "content/en"
        weight = 1

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Home"
            pre = "<i class='bi bi-house-fill'> </i>"
            weight = 1
            url = "/"

            [[languages.en.menu.main]]
            name = "About"
            pre = "<i class='bi bi-person-fill'></i>"
            weight = 4
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            pre = "<i class='bi bi-journals'></i>"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Photos"
            pre = "<i class='bi bi-camera-fill'></i>"
            weight = 3
            url = "photos/"

            [[languages.en.menu.main]]
            name = "Contact"
            pre = "<i class='bi bi-envelope-fill'></i>"
            weight = 5
            url = "contact/"

    [languages.tr]
        languagename = "TR"
        title = "Alper Orus"
        contentDir = "content/tr"
        weight = 2

        [languages.tr.params]
            author = "Alper Orus"
            description = "Alper Orus Kişisel Web Sitesi"
            keywords = "alper, orus, eorus, blog, tasarım, fotoğraf, geliştirme, wordpress, hugo, linux"
            info = "Ön Yüz Geliştirici, Fotoğrafçı, Blog Yazarı ve Tutkulu Linux Meraklısı"
            footercontent = "Bir aktiviteye aşık olun ve yapın! Yaşamın ne olduğunu hiç kimse bilmiyor ve bunun hiçbir önemi yok. "

        [languages.tr.menu]


            [[languages.tr.menu.main]]
            name = "Ana Sayfa"
            pre = "<i class='bi bi-house-fill'> </i>"
            weight = 1
            url = "/"

            [[languages.tr.menu.main]]
            name = "Hakkimda"
            pre = "<i class='bi bi-person-fill'> </i>"
            weight = 4
            url = "hakkimda/"

            [[languages.tr.menu.main]]
            name = "Yazılar"
            pre = "<i class='bi bi-journals'></i>"
            weight = 2
            url = "posts/"

            [[languages.tr.menu.main]]
            name = "Fotoğraflar"
            pre = "<i class='bi bi-camera-fill'></i>"
            weight = 3
            url = "photos/"

            [[languages.tr.menu.main]]
            name = "İletişim"
            pre = "<i class='bi bi-envelope-fill'> </i>"
            weight = 5
            url = "iletisim/"

            [[languages.tr.menu.footer]]
            name = "İletişim"
            pre = "<i class='bi bi-envelope-fill'> </i>"
            weight = 2
            url = "iletisim/"


[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files
disableToc = "false"
